# Generated by Django 2.0.5 on 2018-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('第一大题', models.IntegerField()),
                ('第二大题', models.IntegerField()),
                ('第三大题', models.IntegerField()),
                ('第四大题', models.IntegerField()),
                ('第五大题', models.IntegerField()),
                ('总分', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
